---

- name: Using a template
  hosts: web
  tasks:

    - name: Deploy motd template
      template:
        src: motd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: 0755

